In [22]:
import numpy as np


In [23]:
N = 4
e = np.identity(N)
print(f"e = \n{e}")

#C4
c4 = np.array([[0, 1, 0, 0], [0,0,1,0], [0,0,0,1], [1,0,0,0]], dtype=float)
print(f"c4 = \n{c4}")
c4_inv = np.linalg.inv(c4)
print(f"c4_inv = \n{c4_inv}")

#C2
c2 = np.array([[0, 0, 1, 0], [0,0,0,1], [1,0,0,0], [0,1,0,0]], dtype=float)
print(f"c2 = \n{c2}")

#sigma reflections
sx = np.array([[0, 0, 1, 0], [0,1,0,0], [1,0,0,0], [0,0,0,1]], dtype=float)
sy = np.array([[1, 0, 0, 0], [0,0,0,1], [0,0,1,0], [0,1,0,0]], dtype=float)
print(f"sx = \n{sx}")
print(f"sy = \n{sy}")

sd = np.array([[0, 1, 0, 0], [1,0,0,0], [0,0,0,1], [0,0,1,0]], dtype=float)
sd_prime = np.array([[0, 0, 0, 1], [0,0,1,0], [0,1,0,0], [1,0,0,0]], dtype=float)
print(f"sd = \n{sd}")
print(f"sd_prime = \n{sd_prime}")

e = 
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
c4 = 
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]]
c4_inv = 
[[0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
c2 = 
[[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]
sx = 
[[0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]]
sy = 
[[1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]]
sd = 
[[0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]]
sd_prime = 
[[0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]]


In [24]:
P_A1 = 1/8 * (e + c4 + c4_inv + c2 + sx + sy + sd + sd_prime)
print(f"P_A1 = \n{P_A1}")
P_A2 = 1/8 * (e + c4 + c4_inv + c2 - sx - sy - sd - sd_prime)
print(f"P_A2 = \n{P_A2}")
P_B1 = 1/8 * (e - c4 - c4_inv + c2 + sx + sy - sd - sd_prime)
print(f"P_B1 = \n{P_B1}")
P_B2 = 1/8 * (e - c4 - c4_inv + c2 - sx - sy + sd + sd_prime)
print(f"P_B2 = \n{P_B2}")
P_E = 2/8 * (2*e - 2*c2)
print(f"P_E = \n{P_E}")

P_A1 = 
[[0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]]
P_A2 = 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
P_B1 = 
[[ 0.25 -0.25  0.25 -0.25]
 [-0.25  0.25 -0.25  0.25]
 [ 0.25 -0.25  0.25 -0.25]
 [-0.25  0.25 -0.25  0.25]]
P_B2 = 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
P_E = 
[[ 0.5  0.  -0.5  0. ]
 [ 0.   0.5  0.  -0.5]
 [-0.5  0.   0.5  0. ]
 [ 0.  -0.5  0.   0.5]]


In [25]:
eval, evecs = np.linalg.eig(P_A1)
print("A1")
print(f"eval = \n{eval}")
print(f"evecs = \n{evecs}")
evals, evecs = np.linalg.eig(P_A2)
print("A2")
print(f"eval = \n{eval}")
print(f"evecs = \n{evecs}")
evals, evecs = np.linalg.eig(P_B1)
print("B1")
print(f"eval = \n{eval}")
print(f"evecs = \n{evecs}")
evals, evecs = np.linalg.eig(P_B2)
print("B2")
print(f"eval = \n{eval}")
print(f"evecs = \n{evecs}")
evals, evecs = np.linalg.eig(P_E)
print("E")
print(f"eval = \n{evals}")
print(f"evecs = \n{evecs}")

A1
eval = 
[ 0.00000000e+00  1.00000000e+00 -4.79501157e-35  0.00000000e+00]
evecs = 
[[-0.8660254   0.5         0.86517865  0.8660254 ]
 [ 0.28867513  0.5        -0.25229548 -0.28867513]
 [ 0.28867513  0.5        -0.30644159 -0.28867513]
 [ 0.28867513  0.5        -0.30644159 -0.28867513]]
A2
eval = 
[ 0.00000000e+00  1.00000000e+00 -4.79501157e-35  0.00000000e+00]
evecs = 
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
B1
eval = 
[ 0.00000000e+00  1.00000000e+00 -4.79501157e-35  0.00000000e+00]
evecs = 
[[-0.8660254  -0.5        -0.8660254  -0.8647342 ]
 [-0.28867513  0.5        -0.28867513 -0.24367506]
 [ 0.28867513 -0.5         0.28867513  0.31052957]
 [-0.28867513  0.5        -0.28867513 -0.31052957]]
B2
eval = 
[ 0.00000000e+00  1.00000000e+00 -4.79501157e-35  0.00000000e+00]
evecs = 
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
E
eval = 
[1.00000000e+00 1.11022302e-16 1.00000000e+00 1.11022302e-16]
evecs = 
[[ 0.70710678  0.70710678  0.          0.  